services:

  sitation.defaultcontroller:
    class: Sitation\CustomRuleBundle\Controller\DefaultController
    arguments:
        - '@akeneo_file_storage.file_storage.file.file_storer'       

  sitation.action_applier.pattern:
    class: Sitation\CustomRuleBundle\Controller\PatternActionApplier
    arguments:
      - '@pim_catalog.updater.property_setter'
    tags:
      - { name: akeneo_rule_engine.action_applier, priority: 100 }

  sitation.action_denormalizer.pattern:
    class: Sitation\CustomRuleBundle\Controller\PatternActionDenormalizer
    tags:
      - { name: 'pimee_catalog_rule.denormalizer.product_rule' }

  sitation.validator.existing_attributes:
    class: Sitation\CustomRuleBundle\Controller\ExistingAttributesValidator
    arguments:
      - '@pim_catalog.repository.attribute'
    tags:
      - { name: validator.constraint_validator, alias: pimee_constraint_attributes_validator }

  sitation.action_applier.image_customisation:
    class: Sitation\CustomRuleBundle\Controller\ImageCustomisationActionApplier
    arguments:
      - '@pim_catalog.updater.property_setter'
      - '@Psr\Log\LoggerInterface'
      - '@akeneo_file_storage.file_storage.file.file_storer'
      - '%catalog_storage_dir%'
    tags:
      - { name: akeneo_rule_engine.action_applier, priority: 101 }    

  sitation.action_denormalizer.image_customisation:
    class: Sitation\CustomRuleBundle\Controller\ImageCustomisationActionDenormailzer
    tags:
      - { name: 'pimee_catalog_rule.denormalizer.product_rule' } 

  